### ISSUE TITLE
Handling of np.array with one dimension only.

### ISSUE THREAD

**Issue by oskrgab** [xlwings/xlwings-server#160]
There is an IndexError when writing np.arrays that have one dimension only, i.e. shape = (x, ). This is a common result in machine learning workflows, specially when running the predict method on an estimator.

<img width="709" alt="image" src="https://github.com/user-attachments/assets/9718d9df-b1a8-4184-93a2-756c308d0734">

The image shows a possible solution. This has some drawbacks, though, as the user could force the array to have a shape of (x, 1), and then it would work without modification to the object in the screenshot. The problem with letting the user doing is that might lead to lots of conversions to get the desired result, and it might break the consistency across user's workflows who might expect this to work out of the box.

**Comment by fzumstein** [comment]
Oops, looks like too many DataFrames let you forget how numpy works...
I'd suggest an easier solution that will also cover higher order arrays, see #161
