### ISSUE TITLE
Handle files path with reference to __file__

### ISSUE THREAD

**Issue by bhernandezc** [xlwings/xlwings-server#192]
I notice that when running `python run.py init` on windows server 2016, it shows an error such as the following:

![image](https://github.com/user-attachments/assets/70b56c01-90bc-407c-bf89-e5429e61959b)

This is because the file paths are not relative to the __file__, I suggest ussing Path(__file__).parent.resolve() to be precise and avoid getting this error for all file path

**Comment by fzumstein** [comment]
Awesome, thanks for reporting!

**Comment by fzumstein** [comment]
There was actually a bunch of other issues related to file path on Windows, but they should now all be resolved with 0.9.1, see https://server.xlwings.org/en/latest/changelog/#dec-8-2024
